//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Weather {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaldBeardedBuilder.WeatherExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string celsius {
            get {
                return ResourceManager.GetString("celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weather.
        /// </summary>
        public static string current_weather {
            get {
                return ResourceManager.GetString("current_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code or city, state, country for the default weather location.
        /// </summary>
        public static string default_location_description {
            get {
                return ResourceManager.GetString("default_location_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city, state, country (e.g. Nashville, TN, US).
        /// </summary>
        public static string default_location_placeholder {
            get {
                return ResourceManager.GetString("default_location_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Location.
        /// </summary>
        public static string default_location_title {
            get {
                return ResourceManager.GetString("default_location_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string dockband_title {
            get {
                return ResourceManager.GetString("dockband_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current weather and forecast information.
        /// </summary>
        public static string extension_description {
            get {
                return ResourceManager.GetString("extension_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string extension_name {
            get {
                return ResourceManager.GetString("extension_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string fahrenheit {
            get {
                return ResourceManager.GetString("fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        public static string feels_like {
            get {
                return ResourceManager.GetString("feels_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string one_hour {
            get {
                return ResourceManager.GetString("one_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string kmh {
            get {
                return ResourceManager.GetString("kmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading weather data....
        /// </summary>
        public static string loading_data {
            get {
                return ResourceManager.GetString("loading_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found.
        /// </summary>
        public static string location_not_found {
            get {
                return ResourceManager.GetString("location_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string mph {
            get {
                return ResourceManager.GetString("mph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string network_error {
            get {
                return ResourceManager.GetString("network_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No weather data available.
        /// </summary>
        public static string no_data_available {
            get {
                return ResourceManager.GetString("no_data_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations found.
        /// </summary>
        public static string no_locations_found {
            get {
                return ResourceManager.GetString("no_locations_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for &apos;{0}&apos;.
        /// </summary>
        public static string no_results_for {
            get {
                return ResourceManager.GetString("no_results_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weather and forecast.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string precipitation {
            get {
                return ResourceManager.GetString("precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least 3 characters to search.
        /// </summary>
        public static string search_min_chars {
            get {
                return ResourceManager.GetString("search_min_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a postal code or city name....
        /// </summary>
        public static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show multi-day weather forecast.
        /// </summary>
        public static string show_forecast_description {
            get {
                return ResourceManager.GetString("show_forecast_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Forecast.
        /// </summary>
        public static string show_forecast_title {
            get {
                return ResourceManager.GetString("show_forecast_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours.
        /// </summary>
        public static string six_hours {
            get {
                return ResourceManager.GetString("six_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose temperature unit.
        /// </summary>
        public static string temperature_unit_description {
            get {
                return ResourceManager.GetString("temperature_unit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Unit.
        /// </summary>
        public static string temperature_unit_title {
            get {
                return ResourceManager.GetString("temperature_unit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        public static string three_hours {
            get {
                return ResourceManager.GetString("three_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string twelve_hours {
            get {
                return ResourceManager.GetString("twelve_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string tomorrow {
            get {
                return ResourceManager.GetString("tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather unavailable.
        /// </summary>
        public static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to refresh weather data.
        /// </summary>
        public static string update_interval_description {
            get {
                return ResourceManager.GetString("update_interval_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        public static string update_interval_title {
            get {
                return ResourceManager.GetString("update_interval_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather service unavailable.
        /// </summary>
        public static string weather_service_error {
            get {
                return ResourceManager.GetString("weather_service_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        public static string wind_direction {
            get {
                return ResourceManager.GetString("wind_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        public static string wind_speed {
            get {
                return ResourceManager.GetString("wind_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose wind speed unit.
        /// </summary>
        public static string wind_speed_unit_description {
            get {
                return ResourceManager.GetString("wind_speed_unit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed Unit.
        /// </summary>
        public static string wind_speed_unit_title {
            get {
                return ResourceManager.GetString("wind_speed_unit_title", resourceCulture);
            }
        }
    }
}
